services:
  discord-musicbot:
    build:
      context: .
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_APPLICATION_ID: ${DISCORD_APPLICATION_ID}
    container_name: discord-musicbot
    restart: unless-stopped